version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build-and-upload:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    environment:
      release_notes: "Release notes for this build"
      notify: true
    steps:
      - checkout # check out the code in the working directory
      - run:
          name: Assemble debug build
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
            ./gradlew assembleDebug

workflows:
  testappio-release:
    jobs:
      - build-and-upload:
          filters:
            branches:
              only:
                - main
                - build/circleci
