version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build-and-upload:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    environment:
      release_notes: "Release notes for this build"
      notify: true
      git_release_notes: false
      git_commit_id: false
    steps:
      - checkout # check out the code in the working directory
      - run:
          name: Install JDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - run:
          name: Assemble debug build
          command: ./gradlew assembleDebug
      - run:
          name: Run Unit tests
          command: ./gradlew test
      - run:
          name: Upload to TestApp.io
          command: |
            export INSTALL_DIR=/tmp
            curl -Ls https://github.com/testappio/cli/releases/latest/download/install | bash
            $INSTALL_DIR/ta-cli publish --api_token=cf23fb79-335c-4b3c-b217-1bfd40507c69 --app_id=jgo9jgNE7d --release="android" --apk=./app/build/outputs/apk/debug/app-debug.apk --release_notes=$release_notes --notify=$notify --git_release_notes=$git_release_notes --git_commit_id=$git_commit_id --source="Circle CI"


workflows:
  testappio-release:
    jobs:
      - build-and-upload:
          filters:
            branches:
              only:
                - main
                - build/circleci
