# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    before_all do
        setup_circle_ci
    end

    lane :test do
        increment_version_code(
            gradle_file_path: "project/build.gradle",
        )
    end

    desc "Build debug and test APK for screenshots"
        lane :build_for_screengrab do
        gradle(
          task: 'clean'
        )
        build_android_app(
          task: 'assemble',
          build_type: 'Debug'
        )
        build_android_app(
          task: 'assemble',
          build_type: 'AndroidTest'
        )
    end

    desc "Run sample test functions tests"
    lane :sample_test_functions do
        gradle(task: "app:testDebugUnitTest --tests com.example.theaudiodbapp.utils.SampleTestFunctionsKtTest")
    end

    desc "Run MainActivity ui tests"
    lane :ui_tests_main_activity do
        gradle(task: "app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.theaudiodbapp.MainActivityTest")
    end

    desc "Run HomeFragment ui tests"
    lane :ui_tests_home_fragment do
        gradle(task: "app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.theaudiodbapp.ui.home.HomeFragmentTest")
    end

    desc "Run continuous integration processes"
        lane :ci_processes do
            say("Voulez-vous vraiment exécuter les processus d'intégration continue ?")
            if prompt(text: "Voulez-vous vraiment exécuter les processus d'intégration continue ? (y/n)", ci_input: 'y') == 'y'
                sample_test_functions
                ui_tests_main_activity
                ui_tests_home_fragment
            else
                say("Processus d'intégration continue annulés.")
                puts "Processus d'intégration continue annulés."
            end
        end
    desc "Generate  screenshots"
    lane :screenshots do
        build
        capture_android_screenshots
    end

    desc "Discord Integration"
    lane :discord_notifier do
      discord_notifier(
        webhook_url: ENV["DISCORD_KEY"],
        title: "Discord Notification",
        description: "Circle CI Success",
        thumbnail_url:"https://cdn.discordapp.com/embed/avatars/0.png",
        image_url:"https://cdn.discordapp.com/embed/avatars/0.png",
      )
    end


end
