# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    before_all do
        setup_circle_ci
    end

    desc "Run sample test functions tests"
    lane :sample_test_functions do
        gradle(task: "app:testDebugUnitTest --tests com.example.theaudiodbapp.utils.SampleTestFunctionsKtTest")
    end

    desc "Run MainActivity ui tests"
    lane :ui_tests_main_activity do
        gradle(task: "app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.theaudiodbapp.MainActivityTest")
    end

    desc "Run HomeFragment ui tests"
    lane :ui_tests_home_fragment do
        gradle(task: "app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.theaudiodbapp.ui.home.HomeFragmentTest")
    end

    desc "Run continuous integration processes"
    lane :ci_processes do
        sample_test_functions
        ui_tests_main_activity
        ui_tests_home_fragment
    end

    desc "Discord Integration"
    lane :discord_notifier do
      discord_notifier(
        webhook_url: ENV["DISCORD_KEY"],
        title: "Discord Notification",
        description: "Circle CI Success",
        success: true,
        thumbnail_url:"https://cdn.discordapp.com/embed/avatars/0.png",
        image_url:"https://cdn.discordapp.com/embed/avatars/0.png",
        fields:[
          {
            name:"Field1",
            value:"Value1"
          },
          {
            name:"Field2",
            value:"Value2",
            inline: true
          },
          {
            name:"Field3",
            value:"Value3",
            inline: true
          }
        ]
      )
    end

end
