package com.example.theaudiodbapp.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
class Album(
    val idAlbum: String,
    val idArtist: String,
    val idLabel: String,
    val intLoved: String,
    val intSales: String,
    val intScore: String?,
    val intScoreVotes: String?,
    val intYearReleased: String,
    val strAlbum: String,
    val strAlbum3DCase: String,
    val strAlbum3DFace: String,
    val strAlbum3DFlat: String,
    val strAlbum3DThumb: String,
    val strAlbumCDart: String,
    val strAlbumSpine: String,
    val strAlbumStripped: String,
    val strAlbumThumb: String,
    val strAlbumThumbBack: String,
    val strAlbumThumbHQ: String,
    val strAllMusicID: String,
    val strAmazonID: String,
    val strArtist: String,
    val strArtistStripped: String,
    val strBBCReviewID: String,
    val strDescription: String,
    val strDescriptionCN: String,
    val strDescriptionDE: String,
    val strDescriptionEN: String,
    val strDescriptionES: String,
    val strDescriptionFR: String,
    val strDescriptionHU: String,
    val strDescriptionIL: String,
    val strDescriptionIT: String,
    val strDescriptionJP: String,
    val strDescriptionNL: String,
    val strDescriptionNO: String,
    val strDescriptionPL: String,
    val strDescriptionPT: String,
    val strDescriptionRU: String,
    val strDescriptionSE: String,
    val strDiscogsID: String,
    val strGeniusID: String,
    val strGenre: String,
    val strItunesID: String,
    val strLabel: String,
    val strLocation: String,
    val strLocked: String,
    val strLyricWikiID: String,
    val strMood: String,
    val strMusicBrainzArtistID: String,
    val strMusicBrainzID: String,
    val strMusicMozID: String,
    val strRateYourMusicID: String,
    val strReleaseFormat: String,
    val strReview: String,
    val strSpeed: String,
    val strStyle: String,
    val strTheme: String,
    val strWikidataID: String,
    val strWikipediaID: String
) : Parcelable